import type { Person, Meeting } from '../types'

export const SEED_PEOPLE: Person[] = [
  { id: 'p1',  name: 'Anthony Tozzi',          platform: true,  mic1: true,  mic2: true,  audio: true,  video: false, backup: false, vc: true,  availability_status: 'Available' },
  { id: 'p2',  name: 'Chad Simonovic',          platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p3',  name: 'Charlie Stewart',         platform: true,  mic1: true,  mic2: true,  audio: false, video: false, backup: false, vc: false, availability_status: 'Available' },
  { id: 'p4',  name: 'Chris Whitfield',         platform: true,  mic1: true,  mic2: true,  audio: false, video: false, backup: false, vc: true,  availability_status: 'Available' },
  { id: 'p5',  name: 'Daelan Mitchell',         platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p6',  name: 'Dara Bun',                platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p7',  name: 'Elijah Fletcher',         platform: true,  mic1: true,  mic2: true,  audio: false, video: false, backup: false, vc: true,  availability_status: 'Available' },
  { id: 'p8',  name: 'Gordon Soldi',            platform: true,  mic1: true,  mic2: true,  audio: false, video: false, backup: false, vc: false, availability_status: 'Available' },
  { id: 'p9',  name: 'Grant Reynolds',          platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: false, vc: true,  availability_status: 'Available' },
  { id: 'p10', name: 'Hadyn Dickson',           platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p11', name: 'Harley Newton',           platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p12', name: 'Ivan Van der Poel',       platform: true,  mic1: true,  mic2: true,  audio: true,  video: false, backup: false, vc: true,  availability_status: 'Available' },
  { id: 'p13', name: 'Jack Lean',               platform: false, mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p14', name: 'Jade Godoy',              platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p15', name: 'Jake Jacobson',           platform: true,  mic1: true,  mic2: true,  audio: true,  video: false, backup: false, vc: true,  availability_status: 'Available' },
  { id: 'p16', name: 'Jameel Castelino',        platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p17', name: 'Jeff Howells',            platform: true,  mic1: true,  mic2: true,  audio: true,  video: false, backup: false, vc: false, availability_status: 'Available' },
  { id: 'p18', name: 'Jesse Macdonald',         platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p19', name: 'Joel Fletcher',           platform: true,  mic1: true,  mic2: true,  audio: false, video: false, backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p20', name: 'Jonathan Papandrea',      platform: true,  mic1: false, mic2: false, audio: false, video: false, backup: false, vc: true,  availability_status: 'Available' },
  { id: 'p21', name: 'Jonathan Sheedy',         platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p22', name: 'Karl Furtner',            platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p23', name: 'Marcel Bruinette',        platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p24', name: 'Mark Fletcher',           platform: true,  mic1: true,  mic2: true,  audio: false, video: false, backup: false, vc: true,  availability_status: 'Available' },
  { id: 'p25', name: 'Micah Johnson',           platform: true,  mic1: true,  mic2: true,  audio: true,  video: false, backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p26', name: 'Micah Papandrea',         platform: true,  mic1: true,  mic2: true,  audio: true,  video: false, backup: false, vc: true,  availability_status: 'Available' },
  { id: 'p27', name: 'Pengcheng (Benny) Bi',   platform: true,  mic1: true,  mic2: true,  audio: true,  video: false, backup: false, vc: true,  availability_status: 'Available' },
  { id: 'p28', name: 'Phoenix Dickson',         platform: true,  mic1: true,  mic2: true,  audio: true,  video: true,  backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p29', name: 'Rod Thew',                platform: true,  mic1: true,  mic2: true,  audio: true,  video: false, backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p30', name: 'Simon Dunn',              platform: true,  mic1: true,  mic2: true,  audio: true,  video: false, backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p31', name: 'Steve Fotoudis',          platform: true,  mic1: true,  mic2: true,  audio: false, video: false, backup: false, vc: true,  availability_status: 'Available' },
  { id: 'p32', name: 'Wayne McGregor',          platform: true,  mic1: true,  mic2: true,  audio: true,  video: false, backup: true,  vc: true,  availability_status: 'Available' },
  { id: 'p33', name: 'William Wilkinson',       platform: true,  mic1: true,  mic2: true,  audio: false, video: false, backup: false, vc: true,  availability_status: 'Available' },
]

// People ID map (for reference):
// p1=Anthony Tozzi, p2=Chad Simonovic, p3=Charlie Stewart, p4=Chris Whitfield
// p5=Daelan Mitchell, p6=Dara Bun, p7=Elijah Fletcher, p8=Gordon Soldi
// p9=Grant Reynolds, p10=Hadyn Dickson, p11=Harley Newton, p12=Ivan Van der Poel
// p13=Jack Lean, p14=Jade Godoy, p15=Jake Jacobson, p16=Jameel Castelino
// p17=Jeff Howells, p18=Jesse Macdonald, p19=Joel Fletcher, p20=Jonathan Papandrea
// p21=Jonathan Sheedy, p22=Karl Furtner, p23=Marcel Bruinette, p24=Mark Fletcher
// p25=Micah Johnson, p26=Micah Papandrea, p27=Pengcheng (Benny) Bi, p28=Phoenix Dickson
// p29=Rod Thew, p30=Simon Dunn, p31=Steve Fotoudis, p32=Wayne McGregor, p33=William Wilkinson

export const SEED_MEETINGS: Meeting[] = [
  { id: 'm1',  date: '2026-04-08', type: 'Midweek', status: 'Completed', backupRequired: true,
    planned:     { platform: 'p7',  mic1: 'p27', mic2: 'p26', audio: 'p29', video: 'p14', backup: 'p18', vc: 'p32' },
    completions: { platform: {actual:'p7',  noshow:false}, mic1: {actual:'p27', noshow:false}, mic2: {actual:'p26', noshow:false}, audio: {actual:'p29', noshow:false}, video: {actual:'p14', noshow:false}, backup: {actual:'p18', noshow:false}, vc: {actual:'p32', noshow:false} } },
  { id: 'm2',  date: '2026-04-11', type: 'Weekend', status: 'Completed', backupRequired: true,
    // vc: Peter Board not in roster — left unassigned
    planned:     { platform: 'p2',  mic1: 'p13', mic2: 'p24', audio: 'p12', video: 'p22', backup: 'p1' },
    completions: { platform: {actual:'p2',  noshow:false}, mic1: {actual:'p13', noshow:false}, mic2: {actual:'p24', noshow:false}, audio: {actual:'p12', noshow:false}, video: {actual:'p22', noshow:false}, backup: {actual:'p1',  noshow:false}, vc: {actual:'', noshow:false} } },
  { id: 'm3',  date: '2026-04-15', type: 'Midweek', status: 'Completed', backupRequired: false,
    planned:     { platform: 'p31', mic1: 'p19', mic2: 'p32', audio: 'p1',  video: 'p28', vc: 'p29' },
    completions: { platform: {actual:'p31', noshow:false}, mic1: {actual:'p19', noshow:false}, mic2: {actual:'p32', noshow:false}, audio: {actual:'p1',  noshow:false}, video: {actual:'p28', noshow:false}, vc: {actual:'p29', noshow:false} } },
  { id: 'm4',  date: '2026-04-18', type: 'Weekend', status: 'Completed', backupRequired: true,
    planned:     { platform: 'p23', mic1: 'p25', mic2: 'p33', audio: 'p15', video: 'p16', vc: 'p13' },
    completions: { platform: {actual:'p23', noshow:false}, mic1: {actual:'p25', noshow:false}, mic2: {actual:'p33', noshow:false}, audio: {actual:'p15', noshow:false}, video: {actual:'p16', noshow:false}, backup: {actual:'', noshow:false}, vc: {actual:'p13', noshow:false} } },
  { id: 'm5',  date: '2026-04-22', type: 'Midweek', status: 'Completed', backupRequired: true,
    planned:     { platform: 'p21', mic1: 'p3',  mic2: 'p18', audio: 'p11', video: 'p2',  backup: 'p27', vc: 'p5' },
    completions: { platform: {actual:'p21', noshow:false}, mic1: {actual:'p3',  noshow:false}, mic2: {actual:'p18', noshow:false}, audio: {actual:'p11', noshow:false}, video: {actual:'p2',  noshow:false}, backup: {actual:'p27', noshow:false}, vc: {actual:'p5',  noshow:false} } },
  { id: 'm6',  date: '2026-04-25', type: 'Weekend', status: 'Completed', backupRequired: true,
    planned:     { platform: 'p5',  mic1: 'p8',  mic2: 'p18', audio: 'p26', video: 'p21', backup: 'p2',  vc: 'p28' },
    completions: { platform: {actual:'p5',  noshow:false}, mic1: {actual:'p8',  noshow:false}, mic2: {actual:'p18', noshow:false}, audio: {actual:'p26', noshow:false}, video: {actual:'p21', noshow:false}, backup: {actual:'p2',  noshow:false}, vc: {actual:'p28', noshow:false} } },
  { id: 'm7',  date: '2026-04-29', type: 'Midweek', status: 'Completed', backupRequired: false,
    planned:     { platform: 'p32', mic1: 'p33', mic2: 'p1',  audio: 'p2',  video: 'p10', vc: 'p19' },
    completions: { platform: {actual:'p32', noshow:false}, mic1: {actual:'p33', noshow:false}, mic2: {actual:'p1',  noshow:false}, audio: {actual:'p2',  noshow:false}, video: {actual:'p10', noshow:false}, vc: {actual:'p19', noshow:false} } },
  { id: 'm8',  date: '2026-05-02', type: 'Weekend', status: 'Completed', backupRequired: true,
    planned:     { platform: 'p14', mic1: 'p9',  mic2: 'p15', audio: 'p16', video: 'p32', backup: 'p6',  vc: 'p19' },
    completions: { platform: {actual:'p14', noshow:false}, mic1: {actual:'p9',  noshow:false}, mic2: {actual:'p15', noshow:false}, audio: {actual:'p16', noshow:false}, video: {actual:'p32', noshow:false}, backup: {actual:'p6',  noshow:false}, vc: {actual:'p19', noshow:false} } },
  { id: 'm9',  date: '2026-05-06', type: 'Midweek', status: 'Completed', backupRequired: true,
    planned:     { platform: 'p7',  mic1: 'p31', mic2: 'p3',  audio: 'p28', video: 'p21', backup: 'p16', vc: 'p5' },
    completions: { platform: {actual:'p7',  noshow:false}, mic1: {actual:'p31', noshow:false}, mic2: {actual:'p3',  noshow:false}, audio: {actual:'p28', noshow:false}, video: {actual:'p21', noshow:false}, backup: {actual:'p16', noshow:false}, vc: {actual:'p5',  noshow:false} } },
  { id: 'm10', date: '2026-05-09', type: 'Weekend', status: 'Completed', backupRequired: true,
    planned:     { platform: 'p1',  mic1: 'p13', mic2: 'p12', audio: 'p15', video: 'p10', backup: 'p28', vc: 'p23' },
    completions: { platform: {actual:'p1',  noshow:false}, mic1: {actual:'p13', noshow:false}, mic2: {actual:'p12', noshow:false}, audio: {actual:'p15', noshow:false}, video: {actual:'p10', noshow:false}, backup: {actual:'p28', noshow:false}, vc: {actual:'p23', noshow:false} } },
  { id: 'm11', date: '2026-05-13', type: 'Midweek', status: 'Planned', backupRequired: false,
    planned: { platform: 'p2',  mic1: 'p16', mic2: 'p26', audio: 'p29', video: 'p18', vc: 'p10' },
    completions: {} },
  { id: 'm12', date: '2026-05-16', type: 'Weekend', status: 'Planned', backupRequired: true,
    planned: { platform: 'p4',  mic1: 'p28', mic2: 'p15', audio: 'p17', video: 'p22', backup: 'p5',  vc: 'p32' },
    completions: {} },
  { id: 'm13', date: '2026-05-20', type: 'Midweek', status: 'Planned', backupRequired: false,
    planned: { platform: 'p32', mic1: 'p12', mic2: 'p10', audio: 'p18', video: 'p5',  vc: 'p19' },
    completions: {} },
  { id: 'm14', date: '2026-05-23', type: 'Weekend', status: 'Planned', backupRequired: true,
    planned: { platform: 'p8',  mic1: 'p33', mic2: 'p23', audio: 'p1',  video: 'p13', backup: 'p11', vc: 'p6' },
    completions: {} },
  { id: 'm15', date: '2026-05-27', type: 'Midweek', status: 'Planned', backupRequired: false,
    planned: { platform: 'p25', mic1: 'p24', mic2: 'p30', audio: 'p17', video: 'p16', vc: 'p2' },
    completions: {} },
  { id: 'm16', date: '2026-05-30', type: 'Weekend', status: 'Planned', backupRequired: true,
    planned: { platform: 'p10', mic1: 'p1',  mic2: 'p19', audio: 'p12', video: 'p28', backup: 'p13', vc: 'p29' },
    completions: {} },
]
